### PR TITLE
Update requirements.txt

### PR DESCRIPTION
**Pull request by ehsteve**
Updates to requirements. @dbarrous i am confused by why we install padre_meddea and padre_sharp. Don't those get installed with a pip install at run time?

### CODE REVIEW

**Comment by dbarrous** [comment]
> Updates to requirements. @dbarrous i am confused by why we install padre_meddea and padre_sharp. Don't those get installed with a pip install at run time?

@ehsteve So the instrument packages for HERMES are being installed via pip when the processing Lambda container is built (since you can't install packages on runtime), and they're imported as needed at runtime.

My concern is that if we install all the instrument packages as more missions are added, the Lambda container might become too large hence why I just included them in this base image for now. 

I think a good alternative approach might be to maintain a separate requirements file for each set of instrument packages, specific to the mission name. I can then add logic to the build process to select the correct requirements file based on the mission. Let me know if you think that would be a good idea and I can create a few PRs to refactor.

**Comment by ehsteve** [comment]
My concern is that this is also the container that we develop in. In that case we need to do a local pip install to work on the branch we are working on and so i worry that someone might be confused that their instrument repo is already in there and it's upstraim main branch and not their fork.

**Comment by dbarrous** [comment]
> My concern is that this is also the container that we develop in. In that case we need to do a local pip install to work on the branch we are working on and so i worry that someone might be confused that their instrument repo is already in there and it's upstraim main branch and not their fork.

That's fair, I think in that case I'll create a PR to update the Processing lambda requirements and another to remove the instrument packages from this requirements.txt to avoid that issue

**Review by dbarrous — APPROVED** [review]
These changes look good to me!

**Pull request merged**
